### ISSUE TITLE
Code for the application of your method to the image classification task

### ISSUE THREAD

**Issue by kejie-cn** [tjddus9597/LabelRelaxation-CVPR21#3]
Hello, thanks for your great work, could you please also provide the code for the application of your method to the image classification task?

**Comment by sung-yeon-kim** [comment]
I'm really sorry for the late reply.
Image classification experiment was performed by putting the code of our loss in the code of the CRD repository, which is an great repository for knowledge distillation ([RepDistiller: CRD repository](https://github.com/HobbitLong/RepDistiller))

You only need to modify the names of the variables in the code, and there will not be much to modify.
If you need related experiments, please refer to the repository above.
We will upload the code for image classification later. Thanks for your interest. :)
