### ISSUE TITLE
improve the accuracy71.8----72.1

### ISSUE THREAD

**Issue by zhanghanqi** [tjddus9597/LabelRelaxation-CVPR21#4]
lr=0.0001, weight_decay=0.0001, cub embedding-size=512, optim=adamw The target accuracy rate should be 72.1. After running many experiments, it is only 71.8. Are there any tips to improve the accuracy rate to 72.1?

**Comment by kdwonn** [comment]
Sorry for the late reply.  Actually, a variation of about 0.3 in accuracy could easily appear due to randomness of code/difference of device and environment. Running the code multiple times will give you a similar accuracy as reported.

Thank you!
