### ISSUE TITLE
Code Bugs Gathering

### ISSUE THREAD

**Issue by JoJoistheBestOne** [tjddus9597/LabelRelaxation-CVPR21#5]
Dear authors.
Recently, I read your very talented work.  below is the miss-spelling I have found, would you be very kind to check those points?
Thanks.

https://github.com/tjddus9597/LabelRelaxation-CVPR21/blob/main/code/ET_losses.py#L26
td -> sd

https://github.com/tjddus9597/LabelRelaxation-CVPR21/blob/main/code/ET_losses.py#L57
missing self

https://github.com/tjddus9597/LabelRelaxation-CVPR21/blob/main/code/ET_losses.py#L68-L69
target -> t_emb
source -> s_emb

**Comment by sung-yeon-kim** [comment]
Thank you so much for your interest and attention. :D
All points you checked and corrected are all correct.
It seems that a lot of mistakes were made while editing the name of the variable before uploading the code.

Once again, thank you for your work, and I will fix the code right away.
